language: node_js
node_js:
  - lts/*
install:
  - yarn install
script:
  - cd $TRAVIS_BUILD_DIR/pages && yarn docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
branches:
  only:
  - master
