language: node_js
node_js:
  - lts/*
install:
  - yarn global add vuepress
script:
  - cd $TRAVIS_BUILD_DIR/pages && vuepress build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
