name: Build and Deploy VuePress

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Build with VuePress
        run: yarn docs:build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vuepress-site
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ needs.build.outputs.pages_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy to GitHub Pages
        uses: actions/deploy-to-github-pages@v1
        with:
          branch: gh-pages
          folder: ./docs
