name: Build and Deploy VuePress

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Build VuePress site
        run: yarn docs:build

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages
          folder: ./docs

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: vuepress-site
          path: ./docs
