name: Build and Deploy VuePress

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Build with VuePress
        run: yarn docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: $
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        id: deployment
        with:
          folder: ./docs
